// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJgMLrC_3BEzy4pm8-q2HPfgekpjO1crQ',
    appId: '1:605582555198:web:669fb34978b910df40796f',
    messagingSenderId: '605582555198',
    projectId: 'firefighter-32a0e',
    authDomain: 'firefighter-32a0e.firebaseapp.com',
    storageBucket: 'firefighter-32a0e.appspot.com',
    measurementId: 'G-BTCDV6GGHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCalJUXai-bv1UgCGvM_DLBhkuaNSGkHGQ',
    appId: '1:605582555198:android:dc7a25534e716c8040796f',
    messagingSenderId: '605582555198',
    projectId: 'firefighter-32a0e',
    storageBucket: 'firefighter-32a0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3VxuKj278Pz0HO9V5ZnRMs4OGXFeUUlM',
    appId: '1:605582555198:ios:4ed94d85906d20d840796f',
    messagingSenderId: '605582555198',
    projectId: 'firefighter-32a0e',
    storageBucket: 'firefighter-32a0e.appspot.com',
    iosClientId: '605582555198-v0g3mf9oms0f0cndetit5o0is7745ebg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firefighter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3VxuKj278Pz0HO9V5ZnRMs4OGXFeUUlM',
    appId: '1:605582555198:ios:4ed94d85906d20d840796f',
    messagingSenderId: '605582555198',
    projectId: 'firefighter-32a0e',
    storageBucket: 'firefighter-32a0e.appspot.com',
    iosClientId: '605582555198-v0g3mf9oms0f0cndetit5o0is7745ebg.apps.googleusercontent.com',
    iosBundleId: 'com.example.firefighter',
  );
}
